# Generated by Django 4.1.7 on 2023-04-11 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_rename_picture_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num_likes',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
