# Generated by Django 4.1.7 on 2023-04-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_num_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='num_likes',
            new_name='likes',
        ),
    ]
