# Generated by Django 4.1.7 on 2023-04-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_likes_remove_post_publish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='news_likes',
            new_name='post_likes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='news_likes_count',
            new_name='post_likes_count',
        ),
    ]
