# Generated by Django 4.1.7 on 2023-04-15 14:28

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 300], upload_to='profile_pics'),
        ),
    ]
